Ajusta tokens de line-height e cria helper de conversao para web-only
geekie/geekie-design-system pull request #18
Opened 2023-08-18 17:01 UTC by leocpadua7

# Contexto
Os tokens de line height estão definidos como porcentagem, mas isso não é possível no RN.
Figma com os tokens: https://www.figma.com/file/CGaJEpou7a3NO8N5KX7CSL/Design-System?type=design&node-id=3014-5097&mode=dev

Ajustei os valores dos tokens, e como discutido [nessa thread](https://geekie.slack.com/archives/C300F0A4V/p1692294512354309), criei a função `convertToPx` para resolver o uso dos tokens em casos web-only.

# Mudanças
Os valores dos tokens de line-height foram alterados de valores relativos, para absolutos.
![Captura de Tela 2023-08-17 às 17 13 47](https://github.com/geekie/geekie-design-system/assets/29842092/5876e12d-b2bf-47bb-af7e-3c82f6f4daa9)
![Captura de Tela 2023-08-17 às 17 13 51](https://github.com/geekie/geekie-design-system/assets/29842092/32bc6d78-6d6a-4986-887d-f35896ccc6c7)

# Como testar
Verifique a documentação no storybook.

2023-08-18 18:46 UTC, gabrielguilhoto requested changes

2023-08-18 18:46 UTC, gabrielguilhoto commented on stories/tokens/typographyTokens.stories.mdx
> +Na web, em casos web-only, o valor do line-height pode ser tanto um valor absoluto, quanto um valor em pixels - `lineHeight: 26` e `lineHeight: 26px`, por exemplo - que resultam em formatações difere
Eu falaria aqui que os valores dos nossos tokens são em pixel, e por isso precisamos da adaptação da adição do px em casos web-only. Eu ressaltaria tb que essa adaptação não é necessária quando se usa um polyfill do RN num arquivo web.

2023-08-18 18:46 UTC, gabrielguilhoto commented on helpers/webOnlyHelpers.ts
> +export const convertToPx = (token: number): string => {
Fiquei na dúvida sobre o nome. Por um lado pensei que poderia ser algo como `toPx`, que é mais curto e tende a ser mais fácil de usar e ler.

Pensando de outra forma, tb teremos um helper para as pré-definições e seria bom esses helpers terem nomes análogos. No caso da função para os presets, acho que chamar de algo como `convertPresetToPx` ficaria confuso, pq não é o preset todo que está tendo o px, mas só uma parte dele.

Daí uma outra opção seria ir menos para o concreto da conversão para px e mais para o abstrato da adaptação para estilo web-only. Talvez algo como `convertToWebToken` e `convertToWebPreset` (quem sabe mudando o "convertTo" pra algo mais curto).

2023-08-21 12:19 UTC, leocpadua7 commented on helpers/webOnlyHelpers.ts
> +export const convertToPx = (token: number): string => {
Acho que vale ir pra um nome descritivo, como o `convertToWebToken ` - pensei em encurtar para `toWebToken`, seguindo a ideia do primeiro ponto.

2023-08-21 12:19 UTC, leocpadua7 commented on stories/tokens/typographyTokens.stories.mdx
> +Na web, em casos web-only, o valor do line-height pode ser tanto um valor absoluto, quanto um valor em pixels - `lineHeight: 26` e `lineHeight: 26px`, por exemplo - que resultam em formatações difere
Boa!

2023-08-21 14:01 UTC, merged