Documenta presets e adiciona helper para transformar presets para web
geekie/geekie-design-system pull request #21
Opened 2023-08-24 12:26 UTC by leocpadua7

# Contexto
Esse PR cria um documento para documentar os presets de tipografia. E, para exibir os estilos, cria um helper - `toWebPreset` - para converter valores absolutos em pixel, nos casos de uso web-only. 

# Mudanças
![Captura de Tela 2023-08-24 às 15 03 03](https://github.com/geekie/geekie-design-system/assets/29842092/2e8100af-8aa7-4a9f-a5c9-62d37f63a89a)
![Captura de Tela 2023-08-24 às 15 03 09](https://github.com/geekie/geekie-design-system/assets/29842092/012fbe02-71cb-44ce-af4a-54df3dc0a5ad)
![Captura de Tela 2023-08-24 às 15 03 15](https://github.com/geekie/geekie-design-system/assets/29842092/cafbe354-1875-4c61-908a-5318d32665cb)

# Como testar
Verifique a documentação das pré-definições no storybook;
Verifique que é possível usá-las no SGLearner, em casos web only - com o helper novo.

2023-08-24 21:27 UTC, gabrielguilhoto commented on helpers/webOnlyHelpers.ts
> +      style === 'letterSpacing'
Acredito que seja só o lineHeight que precisava da adição do `px` por existirem semânticas diferentes para a medida com e sem, não?

2023-08-25 18:05 UTC, gabrielguilhoto requested changes

2023-08-25 18:05 UTC, gabrielguilhoto commented on utils/PresetsDocBlock/index.tsx
> +                    tokens[tokenKey] === preset[key as keyof typeof preset] &&
Não era melhor já fazer o cast no `Object.keys(preset)`, de onde o `key` é originalmente definido, em vez de fazer aqui no uso?

2023-08-25 18:05 UTC, gabrielguilhoto commented on utils/PresetsDocBlock/index.tsx
> +type TokensKeys = keyof typeof allTokens;
Nit: acredito que aqui o plural certo seria `TokenKeys`. Aliás, fico na dúvida se faz sentido manter o plural. Normalmente os tipos ficam no singular, né?

E, em vez de `Key`, eu usaria algo como `Name` pra deixar claro que é o nome de um token/preset. `Key` pode dar a entender por exemplo que é alguma chave dentro do preset (`fontFamily`, `fontSize` etc.).

2023-08-25 18:19 UTC, leocpadua7 commented on helpers/webOnlyHelpers.ts
> +  });
Verdade!! Muito melhor assim

2023-08-25 18:19 UTC, leocpadua7 commented on token-presets/index.ts
> +}
Eu tinha criado, pra além dessa razão, para garantir o retorno da função `toWebPreset`.

2023-08-25 18:24 UTC, leocpadua7 commented on utils/PresetsDocBlock/index.tsx
> +                    tokens[tokenKey] === preset[key as keyof typeof preset] &&
Quando mando pra cima, em `Object.keys(preset)`, ele solta um erro na linha 42: `tokens[tokenKey]`.

Um jeito que ele não me traz erro, é fazer o seguinte:
`        {(Object.keys(preset) as PresetNames[]).map((key) => {
          return (
            <div className="token" key={key}>
              <div className="key">{key}:</div>
              <div className="value">
                {(Object.keys(tokens)).map((tokenKey) => {
                  if (
                    tokens[tokenKey as keyof typeof tokens] === preset[key as keyof typeof preset] &&
                    tokenKey
                      .toLowerCase()
                      .replace(/_/g, '')
                      .includes(key.toLowerCase())
                  ) {
                    return tokenKey;
                  }
                  return null;
                })}
              </div>
            </div>
          );
        })}`

2023-08-25 19:03 UTC, gabrielguilhoto commented on token-presets/index.ts
> +}
Pensando só na necessidade dessa função, talvez a tipagem dela poderia ser algo como

```typescript
export const toWebPreset =  <Preset extends { lineHeight: number }>(preset: Preset): Preset & { lineHeight: string } => {
  return { ...preset, lineHeight: toPx(preset.lineHeight) };
};
```

se não quiser criar o tipo do `Preset`.

2023-08-25 19:18 UTC, leocpadua7 commented on utils/PresetsDocBlock/index.tsx
> +        {(Object.keys(preset) as PresetNames[]).map((key) => {
Verdade. Tá errado

2023-08-25 19:28 UTC, leocpadua7 commented on utils/PresetsDocBlock/index.tsx
> +                    tokens[tokenKey as keyof typeof tokens] ===
Deu sim!

2023-08-25 19:28 UTC, leocpadua7 commented on utils/PresetsDocBlock/index.tsx
> +          {(Object.keys(allPresets) as PresetNames[]).map((key) => {
Vale! Fiz as mudanças aqui

2023-08-25 19:29 UTC, leocpadua7 commented on utils/PresetsDocBlock/index.tsx
> +interface Preset {
Mantive a interface pra garantir que recebemos o valor certo aqui

2023-08-25 19:48 UTC, gabrielguilhoto requested changes

2023-08-25 19:48 UTC, gabrielguilhoto commented on helpers/webOnlyHelpers.ts
> +const toPx = (value: number | string): string => {
Pq precisou aceitar string aqui tb?

2023-08-25 19:48 UTC, gabrielguilhoto commented on utils/PresetsDocBlock/index.tsx
> +type PresetNames = keyof typeof allPresets;
Como eu tinha comentado, não vale deixar o tipo aqui no singular como costumamos fazer?

2023-08-25 20:13 UTC, leocpadua7 commented on helpers/webOnlyHelpers.ts
> +const toPx = (value: number | string): string => {
Ah, é coisa que sobrou 🤦

2023-08-25 20:15 UTC, leocpadua7 commented on utils/PresetsDocBlock/index.tsx
> +type PresetNames = keyof typeof allPresets;
Vale sim, acabei esquecendo de arrumar

2023-08-25 20:51 UTC, gabrielguilhoto approved these changes

2023-08-25 21:03 UTC, merged