Criar tokens semânticos + ajustes na build do style dictionary
geekie/geekie-design-system pull request #32
Opened 2024-01-02 19:08 UTC by leocpadua7

# Contexto
Seguindo as definições que fizemos no spike, e na Jenga, sobre o dark mode, adicionei os tokens semânticos e ajustei as configurações de build do style dictionary.

# Mudanças
Foram duas principais:
1. Ajustei a pasta `/src`, divindo entre `core`, com os valores principais, e `semantic` com as definições dos temas;
2. Removi as definições de build estáticas, no `.json`, e deixei todo o fluxo no arquivo `style-dictionary-build.ts`.

# Como testar
Rode `yarn prepare`, e verifique se os arquivos foram criado corretamente em `built-tokens/js/`.

2024-01-03 20:09 UTC, gabrielguilhoto requested changes

2024-01-03 20:09 UTC, gabrielguilhoto commented on tokens/config/style-dictionary-build.ts
> +  source: [`tokens/src/core/**/!(*.${themes.join(`|*.`)}).json`],
A ideia de mover as configurações do `style-dictionary-config.json` para cá foi por causa do `themes` variável, certo? Faz sentido mas fiquei com a impressão de que o código ficou mais difícil de entender dessa forma. Será que valeria levar essas configurações passadas para o `StyleDictionary.extend` para outros arquivos (imagino que ts em vez de json, para poder usar a variável) para separar melhor?

2024-01-03 20:09 UTC, gabrielguilhoto commented on themes/getThemeToken.ts
> +export type ColorValue = string | OpaqueColorValue;
Não entendi muito bem, o que são o `OpaqueColorValue` e o `ColorValue`? E, na tipagem de retorno do `getThemeToken`, por que pode ser uma `string` se o `ColorValue` em si também pode ser string?

2024-01-03 20:14 UTC, leocpadua7 commented on themes/getThemeToken.ts
> +export type ColorValue = string | OpaqueColorValue;
Eu puxei essa tipagem do stylesheet do RN. De fato, acabei removendo esse trecho no #33 . 
Vou ajustar isso aqui agora

2024-01-03 20:15 UTC, leocpadua7 commented on tokens/config/style-dictionary-build.ts
> +  source: [`tokens/src/core/**/!(*.${themes.join(`|*.`)}).json`],
Acho que faz sentido! Vou dar uma lida na documentação, e nos exemplos de configuração da lib, pra entender se existe alguma outra forma de organizar.

De fato, essa mudança tornou a leitura do código um pouco mais complexa

2024-01-04 20:39 UTC, gabrielguilhoto approved these changes

2024-01-04 20:44 UTC, merged